#!/bin/bash

# Copyright 2011-2019 The OTP authors
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e -o pipefail
echo "Call: $*" 1>&2

export DIR="`echo $1 | sed -e 's/--outdir=//'`"
echo "Working dir: '$DIR'" 1>&2
cd $DIR

export COMMAND="java -Dconfig.file=`dirname $0`/config.conf -jar $HOME/cromwell-47.jar run --type CWL $2 -i $3"

echo "Command: '$COMMAND'" 1>&2
echo "" 1>&2

$COMMAND | tee cromwell-output.txt 1>&2

#the tool write all log to stdout, therefore I redirect the output to an file and extract then the json for stdout
cat cromwell-output.txt | awk 'BEGIN { show=0 } show==1 {print $0} /.*SingleWorkflowRunnerActor workflow finished with status.*/ {show=1} /^\}/ {show=0}'
