UPDATE processing_option SET name = 'PIPELINE_RODDY_ALIGNMENT_RNA_DEFAULT_GENOME_STAR_INDEX' WHERE name = 'PIPELINE_RODDY_ALIGNMENT_DEFAULT_GENOME_STAR_INDEX';
UPDATE processing_option SET type = NULL WHERE name = 'PIPELINE_RODDY_ALIGNMENT_RNA_DEFAULT_GENOME_STAR_INDEX';
