ALTER TABLE abstract_quality_assessment
  ADD COLUMN estimated_number_of_cells double precision,
  ADD COLUMN mean_reads_per_cell double precision,
  ADD COLUMN median_genes_per_cell double precision,
  ADD COLUMN number_of_reads double precision,
  ADD COLUMN valid_barcodes double precision,
  ADD COLUMN reads_mapped_confidently_to_transcriptome double precision,
  ADD COLUMN reads_mapped_confidently_to_exonic_regions double precision,
  ADD COLUMN reads_mapped_confidently_to_intronic_regions double precision,
  ADD COLUMN reads_mapped_confidently_to_intergenic_regions double precision,
  ADD COLUMN sequencing_saturation double precision,
  ADD COLUMN q30bases_in_barcode double precision,
  ADD COLUMN q30bases_in_rna_read double precision,
  ADD COLUMN q30bases_in_sample_index double precision,
  ADD COLUMN q30bases_in_umi double precision,
  ADD COLUMN fraction_reads_in_cells double precision,
  ADD COLUMN total_genes_detected double precision,
  ADD COLUMN median_umi_counts_per_cell double precision;
