ALTER TABLE submission RENAME TO ega_submission;

ALTER TABLE submission_sample_submission_object RENAME TO ega_submission_sample_submission_object;
ALTER TABLE ega_submission_sample_submission_object RENAME COLUMN submission_samples_to_submit_id TO ega_submission_samples_to_submit_id;

ALTER TABLE submission_data_file_submission_object RENAME TO ega_submission_data_file_submission_object;
ALTER TABLE ega_submission_data_file_submission_object RENAME COLUMN submission_data_files_to_submit_id TO ega_submission_data_files_to_submit_id;

ALTER TABLE submission_bam_file_submission_object RENAME TO ega_submission_bam_file_submission_object;
ALTER TABLE ega_submission_bam_file_submission_object RENAME COLUMN submission_bam_files_to_submit_id TO ega_submission_bam_files_to_submit_id;
