---
image: grails:2.5.1

variables:
  GRAILS_OPTS: '-Xms1G'

stages:
  - build
  - test
  - war

compile:
  stage: build
  script:
    - grails compile

unit tests:
  stage: test
  image: otp-tests
  before_script:
    - echo 'otp.testing.group=othergroup' > /home/grails/.otp.properties
  script:
    - 'grails test-app unit: -xml'
  artifacts:
    paths:
      - target/test-reports/*.xml
    expire_in: 1 weeks

integration tests:
  stage: test
  image: otp-tests
  before_script:
    - echo 'otp.testing.group=othergroup' > /home/grails/.otp.properties
  script:
    - 'grails test-app integration: -xml'
  artifacts:
    paths:
      - target/test-reports/*.xml
    expire_in: 1 weeks

codenarc:
  stage: test
  script:
    - grails compile
    - grails codenarc
  after_script:
    - sed -i "s@<SourceDirectory></SourceDirectory>@<SourceDirectory>$(pwd)</SourceDirectory>@" target/CodeNarc-Report.xml
  artifacts:
    paths:
      - target/CodeNarc-Report.xml
    expire_in: 1 weeks

war:
  stage: war
  image: otp-tests
  before_script:
    - echo 'otp.testing.group=othergroup' > /home/grails/.otp.properties
    - mkdir -p logs/jobs
  script:
    - 'grails war'
    - md5sum "target/otp.war" | tee "target/otp.war.md5"
    - sha256sum "target/otp.war" | tee "target/otp.war.sha256"
    - git rev-parse HEAD | tee "target/otp.war.gitrev"
  artifacts:
    paths:
      - target/otp.war*
    expire_in: 1 weeks
