---
image: grails:2.5.1

#notes:
# recursive expansion of variables does not work
# having multiple commends in one variable does not work
# putting the expire time to a variable does not work


variables:
  GRAILS_OPTS: '-Xms1G'
  ARTIFACTS_BASE_DIRECTORY: 'artifacts'
  WAR_DIRECTORY: $ARTIFACTS_BASE_DIRECTORY/war
  MAVEN_CACHE: $CI_PROJECT_DIR/.m2
  PREPARE_MAVEN_CACHE1: "mkdir -p $CI_PROJECT_DIR/.m2"
  PREPARE_MAVEN_CACHE2: "ln -s $CI_PROJECT_DIR/.m2 /home/grails/.m2"
#  CI_DEBUG_TRACE: "true"



stages:
  - all



#----------------------------
# templates


.abstract base: &base_template
  stage: all
  image: otp-tests
  dependencies: []
  only:
    - branches
  cache:
    key: "${CI_PROJECT_PATH_SLUG}-maven"
    paths:
      - $MAVEN_CACHE
  artifacts: &artifacts_template
    expire_in: 1 week
  before_script:
    - $PREPARE_MAVEN_CACHE1
    - $PREPARE_MAVEN_CACHE2



.abstract test: &test_template
  <<: *base_template
  before_script:
    - echo 'otp.testing.group=othergroup' > /home/grails/.otp.properties
    - $PREPARE_MAVEN_CACHE1
    - $PREPARE_MAVEN_CACHE2
  script:
    - grails test compile --non-interactive
    - "grails test-app --non-interactive $TEST_TYPE: -coverage de.**.*"
  after_script:
    - head -1 target/test-reports/cobertura/coverage.xml
  coverage: /line-rate="\d.(\d\d)\d+"/
  artifacts: &artifacts_template
    <<: *artifacts_template
    paths:
      - target/test-reports/*.xml
      - target/test-reports/html/
      - target/test-reports/cobertura/coverage.xml
    when: always


#----------------------------
# jobs

unit tests:
  <<: *test_template
  variables:
    TEST_TYPE: unit



integration tests:
  <<: *test_template
  variables:
    TEST_TYPE: integration



codenarc:
  <<: *base_template
  script:
    - grails compile --non-interactive
    - grails codenarc --non-interactive
  after_script:
    - sed -i "s@<SourceDirectory></SourceDirectory>@<SourceDirectory>$(pwd)</SourceDirectory>@" target/CodeNarc-Report.xml
  artifacts:
    <<: *artifacts_template
    paths:
      - target/CodeNarc-Report*
    when: always



war:
  <<: *base_template
  artifacts:
    <<: *artifacts_template
    paths:
      - $ARTIFACTS_BASE_DIRECTORY
  before_script:
    - export CI_COMMIT_REF_NAME
    - export CI_COMMIT_SHA
    - echo 'otp.testing.group=othergroup' > /home/grails/.otp.properties
    - mkdir -p logs/jobs
    - $PREPARE_MAVEN_CACHE1
    - $PREPARE_MAVEN_CACHE2
  script:
    - set -e -o pipefail

    - echo $WAR_DIRECTORY
    - export WAR_FILE=$WAR_DIRECTORY/otp.war

    - 'grails war --non-interactive'

    - mkdir -p $WAR_DIRECTORY
    - mv target/otp.war $WAR_DIRECTORY
    - md5sum "$WAR_FILE" | tee "$WAR_FILE.md5"
    - sha256sum "$WAR_FILE" | tee "$WAR_FILE.sha256"
    - git rev-parse HEAD | tee "$WAR_FILE.gitrev"



test migration:
  <<: *base_template
  image: otp-test-migration
  services:
    - postgres:latest
  variables:
    POSTGRES_DB: otp
    POSTGRES_USER: otp
    POSTGRES_PASSWORD: otp
  before_script:
    - echo 'otp.database.server=postgres' >> /home/grails/.otp.properties
    - echo 'otp.database.port=5432' >> /home/grails/.otp.properties
    - echo 'otp.database.database=otp' >> /home/grails/.otp.properties
    - echo 'otp.database.username=otp' >> /home/grails/.otp.properties
    - echo 'otp.database.password=otp' >> /home/grails/.otp.properties
    - $PREPARE_MAVEN_CACHE1
    - $PREPARE_MAVEN_CACHE2
  script:
    - grails compile --non-interactive
    - grails dbm-update --non-interactive
    - bash ./bashScripts/grails-migration-plugin/create-dbm-gorm-diff-without-false-changes.sh testing
    - bash ./bashScripts/grails-migration-plugin/check-for-changelog-file.sh testing
  artifacts:
    <<: *artifacts_template
    paths:
      - migrations/changelogs/*/testing.groovy
    when: on_failure
