---
image: grails:2.5.1

variables:
  GRAILS_OPTS: '-Xms1G'
  ARTIFACTS_BASE_DIRECTORY: 'deployment-scripts'
  MIGRATION_SCRIPT_PATH: $ARTIFACTS_BASE_DIRECTORY/migration-scripts
  WAR_DIRECTORY: $ARTIFACTS_BASE_DIRECTORY/war
  WAR_FILE: $ARTIFACTS_BASE_DIRECTORY/war/otp.war




stages:
  - all



.abstract only branches: &only_branches
  only:
    - branches

.abstract artifacts: &artifacts_job_template
  <<: *only_branches
  dependencies: []
  artifacts: &artifacts_template
    paths:
      - $ARTIFACTS_BASE_DIRECTORY
    expire_in: 1 week



.abstract test: &test_template
  <<: *only_branches
  stage: all
  image: otp-tests
  dependencies: []
  before_script:
    - echo 'otp.testing.group=othergroup' > /home/grails/.otp.properties
  script:
    - grails test compile
    - "grails test-app $TEST_TYPE: -coverage de.**.*"
  after_script:
    - head -1 target/test-reports/cobertura/coverage.xml
  coverage: /line-rate="\d.(\d\d)\d+"/
  artifacts:
    <<: *artifacts_template
    paths:
      - target/test-reports/*.xml
      - target/test-reports/html/
      - target/test-reports/cobertura/coverage.xml
    when: always

unit tests:
  <<: *test_template
  variables:
    TEST_TYPE: unit

integration tests:
  <<: *test_template
  variables:
    TEST_TYPE: integration


codenarc:
  <<: *only_branches
  stage: all
  dependencies: []
  script:
    - grails compile
    - grails codenarc
  after_script:
    - sed -i "s@<SourceDirectory></SourceDirectory>@<SourceDirectory>$(pwd)</SourceDirectory>@" target/CodeNarc-Report.xml
  artifacts:
    <<: *artifacts_template
    paths:
      - target/CodeNarc-Report.xml
    when: always




war:
  <<: *artifacts_job_template
  stage: all
  image: otp-tests
  before_script:
    - export CI_COMMIT_REF_NAME
    - export CI_COMMIT_SHA
    - echo 'otp.testing.group=othergroup' > /home/grails/.otp.properties
    - mkdir -p logs/jobs
  script:
    - set -e -o pipefail

    - echo $WAR_DIRECTORY
    - echo $WAR_FILE

    - 'grails war'

    - mkdir -p $WAR_DIRECTORY
    - mv target/otp.war $WAR_DIRECTORY
    - md5sum "$WAR_FILE" | tee "$WAR_FILE.md5"
    - sha256sum "$WAR_FILE" | tee "$WAR_FILE.sha256"
    - git rev-parse HEAD | tee "$WAR_FILE.gitrev"
