/*
 * Copyright 2011-2026 The OTP authors
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package de.dkfz.tbi.otp.workflow.alignment.cellRanger

import groovy.util.logging.Slf4j
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.stereotype.Component

import de.dkfz.tbi.otp.dataprocessing.cellRanger.CellRangerQualityAssessment
import de.dkfz.tbi.otp.dataprocessing.cellRanger.CellRangerService
import de.dkfz.tbi.otp.dataprocessing.singleCell.SingleCellBamFile
import de.dkfz.tbi.otp.infrastructure.alignment.CellRangerWorkFileService
import de.dkfz.tbi.otp.qcTrafficLight.QcTrafficLightService
import de.dkfz.tbi.otp.qcTrafficLight.QcTrafficLightValue
import de.dkfz.tbi.otp.utils.CollectionUtils
import de.dkfz.tbi.otp.workflow.TableColumn
import de.dkfz.tbi.otp.workflow.jobs.AbstractQcFileParseJob
import de.dkfz.tbi.otp.workflowExecution.WorkflowStep

import java.nio.file.Path

/**
 * Job to parse CellRanger quality assessment metrics from a QC file (a delimiter separated values file),
 * generated by CellRanger, create or update a CellRangerQualityAssessment object with the parsed values.
 */
@Slf4j
@Component
class CellRangerParseJob extends AbstractQcFileParseJob implements CellRangerShared {

    @Autowired
    CellRangerWorkFileService cellRangerWorkFileService

    @Autowired
    CellRangerService cellRangerService

    @Autowired
    QcTrafficLightService qcTrafficLightService

    @Override
    Path getQcFileToParse(WorkflowStep workflowStep) {
        SingleCellBamFile singleCellBamFile = getBamFile(workflowStep)
        return cellRangerWorkFileService.getQualityAssessmentCsvFile(singleCellBamFile)
    }

    @Override
    Collection<TableColumn> getQcColumns() {
        // Convert CellRanger-specific enum to generic TableColumn objects
        return CellRangerService.MetricsSummaryCsvColumn.values().collect { metricColumn ->
            new TableColumn(metricColumn.columnName, metricColumn.attributeName)
        }
    }

    @Override
    void processQualityAssessment(WorkflowStep workflowStep, Map<String, String> parsedData) {
        SingleCellBamFile singleCellBamFile = getBamFile(workflowStep)
        assert singleCellBamFile: "The SingleCellBamFile associated with the WorkflowStep ${workflowStep.id} is null."

        // Create quality assessment object
        CellRangerQualityAssessment qa = CollectionUtils.atMostOneElement(CellRangerQualityAssessment.findAllWhere([
                abstractBamFile: singleCellBamFile
        ])) ?: new CellRangerQualityAssessment()

        // Set the parsed values on the quality assessment object
        parsedData.each { String attributeName, String value ->
            try {
                qa.setProperty(attributeName, value as Double)
            } catch (NumberFormatException e) {
                throw new NumberFormatException("Failed to parse '${value}' for attribute '${attributeName}'").initCause(e)
            }
        }

        // Set QC traffic light status and save
        qcTrafficLightService.setQcTrafficLightStatusBasedOnThresholdAndProjectSpecificHandling(singleCellBamFile, (QcTrafficLightValue) qa)

        qa.abstractBamFile = singleCellBamFile
        qa.save(flush: true)
    }
}
