
create index processing_step_parameter_processing_step_input_idx on processing_step_parameter(processing_step_input_id);
create index processing_step_parameter_processing_step_output_idx on processing_step_parameter(processing_step_output_id);
create index processing_step_parameter_parameter_idx on processing_step_parameter(parameter_id);

create index processing_step_previous_idx on processing_step(previous_id);
alter index next_idx rename to processing_step_next_idx;
alter index process_idx rename to processing_step_process_idx;

create index processing_step_update_error_idx on processing_step_update(error_id);
alter index date_idx rename to processing_step_update_date_idx;
alter index state_idx rename to processing_step_update_state_idx;
alter index processing_step_idx rename to processing_step_update_processing_step_idx;
