ALTER TABLE cluster_job
  ADD COLUMN date_created TIMESTAMP WITH TIME ZONE,
  ADD COLUMN last_updated TIMESTAMP WITH TIME ZONE;

UPDATE cluster_job SET
  date_created = TIMESTAMP WITH TIME ZONE '1970-01-01 00:00:00+00',
  last_updated = TIMESTAMP WITH TIME ZONE '1970-01-01 00:00:00+00';

ALTER TABLE cluster_job ALTER COLUMN date_created SET NOT NULL;
ALTER TABLE cluster_job ALTER COLUMN last_updated SET NOT NULL;
