#
# Copyright 2011-2026 The OTP authors
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

##ssh
otp.ssh.user=otp
otp.ssh.authMethod=password
otp.ssh.password=otp
otp.ssh.host=openssh-server
otp.ssh.port=2222
otp.ssh.timeout=0
otp.scheduler=LSF

## weskit
otp.wes.url=https://127.0.0.1:8080/ga4gh/wes/v1
otp.wes.data.directory=/tmp
otp.wes.auth.tokenUri=http://127.0.0.1:8080
otp.wes.auth.clientId=otp
otp.wes.auth.clientSecret=123

##oidc
otp.security.oidc.enabled=false
otp.security.oidc.client=dummy
otp.security.oidc.redirectUri=http://127.0.0.1:8080/login/oauth2/code/

## Keycloak Settings for API connection
otp.security.keycloak.server=http://127.0.0.1:8100
otp.security.keycloak.clientId=dummy
otp.security.keycloak.clientSecret=dummy

## properties for tests
otp.testing.group=otpGroup
otp.testing.project.unix.group=otp

## paths: tools & roddy
otp.path.tools=/tmp/tools
otp.path.tools.roddy=/tmp/roddy

## settings for workflow tests
#otp.testing.workflows.init.script added automatically in the ci
