#!/bin/bash

# Copyright 2011-2024 The OTP authors
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# execute local git hooks
if [ -x $0.local ]; then
    $0.local "$@" || exit $?
fi

HOOK_NAME=$(basename $0)
HOOK_FILE=devScripts/git-hooks/${HOOK_NAME}

# execute git hooks in OTP repository
if [ -x ${HOOK_FILE} -a -f ${HOOK_FILE} ]; then
    ${HOOK_FILE} "$@" || exit $?
fi

if [ -d ${HOOK_FILE} ]; then
    for file in ${HOOK_FILE}/*; do
        if [ -x ${file} ]; then
            ${file} "$@" || exit $?
        fi
    done
fi
