#!/bin/bash

# execute local git hooks
if [ -x $0.local ]; then
    $0.local "$@" || exit $?
fi

HOOK_NAME=$(basename $0)
HOOK_FILE=bashScripts/git-hooks/${HOOK_NAME}

# execute git hooks in OTP repository
if [ -x ${HOOK_FILE} -a -f ${HOOK_FILE} ]; then
    ${HOOK_FILE} "$@" || exit $?
fi

if [ -d ${HOOK_FILE} ]; then
    for file in ${HOOK_FILE}/*; do
        if [ -x ${file} ]; then
            ${file} "$@" || exit $?
        fi
    done
fi
