#!/bin/sh

JIRA_HOST=https://$JIRA_URL
JIRA_ISSUE=$1
JIRA_ISSUE_API_LINK=$JIRA_HOST/rest/api/latest/issue/$JIRA_ISSUE
JIRA_TRANSITION_ID_PROGRESS=43
JIRA_TRANSITION_ID_BLOCKED=173
JIRA_COOKIE_FILE=~/.jira-cookie
REVIEWBOARD_LINK=$2
COMMIT_MESSAGE=$(git log -1 HEAD --pretty=format:%s)


retry() {
    echo "Login failed. Please try again!"
    rm -f $JIRA_COOKIE_FILE
    jira-script $JIRA_ISSUE $REVIEWBOARD_LINK
    exit
}


#Checks JIRA Cookie and create a new one if it not exists
if [ ! -f $JIRA_COOKIE_FILE ]; then

    echo "Please enter JIRA username:"
    read -e username
    echo "Please enter JIRA password:"
    read -s password

    generate_post_data() {
        cat <<EOF
{
    "username": "$username",
    "password": "$password"
}
EOF
    }

    curl -s -f \
    --output /dev/null \
    -c $JIRA_COOKIE_FILE \
    -H "Content-Type:application/json" \
    -X POST --data "$(generate_post_data)" \
    "$JIRA_HOST/rest/auth/1/session"

    EXITCODE=$?
    if [ $EXITCODE -ne 0 ]
    then
       retry
    else
       echo "Successful login"
    fi
fi


#Create Link in JIRA to ReviewBoard
generate_link_post_data() {
  cat <<EOF
{
    "globalId": "system=$REVIEWBOARD_LINK",
    "relationship": "ReviewBoard",
    "object": {
        "url":"$REVIEWBOARD_LINK",
        "summary":"$COMMIT_MESSAGE",
        "title":"Review Request:",
        "icon": {
            "url16x16":"https://***REMOVED***reviewboard.dkfz.de/reviews/static/rb/images/favicon.3161c840d49e.ico",
            "title":"Review Board"
        }
    }
}
EOF
}

HTTP_CODE=$(curl -s -w '%{http_code}' \
--output /dev/null \
-b $JIRA_COOKIE_FILE \
-H "Content-Type:application/json" \
-X POST --data "$(generate_link_post_data)" \
"$JIRA_ISSUE_API_LINK/remotelink")

if [ $HTTP_CODE == 201 ]
then
    echo "Successful linked"
elif [ $HTTP_CODE == 401 ]
then
    retry
else
    echo "HTTP-Code $HTTP_CODE"
fi

#Update Issue in JIRA (In Progress -> In Review)
generate_update_post_data() {
  cat <<EOF
{
    "transition": {
        "id":"$JIRA_TRANSITION_ID_PROGRESS"
    }
}
EOF
}

HTTP_CODE=$(curl -s -w '%{http_code}' \
--output /dev/null \
-b $JIRA_COOKIE_FILE \
-H "Content-Type:application/json" \
-X POST --data "$(generate_update_post_data)" \
"$JIRA_ISSUE_API_LINK/transitions?expand=transitions.fields")

if [ $HTTP_CODE == 204 ]
then
    echo "Successful updated"
else

    #Try to update Issue in JIRA (Blocked -> In Review)
    generate_update_post_data() {
        cat <<EOF
{
    "transition": {
        "id":"$JIRA_TRANSITION_ID_BLOCKED"
    }
}
EOF
    }

    HTTP_CODE=$(curl -s -w '%{http_code}' \
    --output /dev/null \
    -b $JIRA_COOKIE_FILE \
    -H "Content-Type:application/json" \
    -X POST --data "$(generate_update_post_data)" \
    "$JIRA_ISSUE_API_LINK/transitions?expand=transitions.fields")

    if [ $HTTP_CODE == 204 ]
    then
        echo "Successful updated"
    else
        echo "HTTP-Code $HTTP_CODE"
    fi
fi