#!/bin/sh

set -e

OTP_NUMBER=`git log -1 --oneline --decorate=false | awk '{print $2}' | sed -e "s/://g"`
if [ "${OTP_NUMBER:0:4}" == "OTP-" ]
then
    RB_OPTS="--bugs-closed $OTP_NUMBER"
fi
rbt_request=$(rbt post -g $RB_OPTS --branch "`git merge-base --fork-point origin/master`" | egrep '^http://***REMOVED***reviewboard\.dkfz\.de/reviews/r/[0-9]+/$')
echo $rbt_request
if [ "$rbt_request" == "" -o "$RB_OPTS" == "" ]
then
    echo ""
    exit 1
fi
jira-script $OTP_NUMBER $rbt_request
